version: "3"
services:
  prometheus:
    build: docker/prometheus/
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./docker/grafana-data:/var/lib/grafana
