- name: Install and config webserver
  hosts: webserver
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
    - name: Install software
      apt:
        name: "{{item}}"
        state: present
      with_items: 
        - php-fpm
        - nginx
        - git
        - php-curl
        - php-zip
        - php-mysql
        - php-gd
    - name: Clone Opencart repo
      git:
        repo: 'https://github.com/opencart/opencart.git'
        dest: /tmp/opencart
    - name: Copy Opencart data
      copy:
        src: /tmp/opencart/upload/
        dest: /home/webroot/
        remote_src: true
        owner: www-data
        mode: u+rwx
    - name: Recopy file for Opencart configuration
      copy:
        remote_src: true
        src: "/home/webroot/{{item}}-dist.php"
        dest: "/home/webroot/{{item}}.php"
        mode: a+rw,u+x
      with_items: 
        - admin/config
        - config
    - name: Delete old copy of opencart config
      file:
        state: absent
        path: "/home/webrrot/{{item}}-dist.php"
      with_items:
        - config
        - admin/config
    - name: Copy nginx config
      copy:
        src: nginx/{{item}}
        dest: /etc/nginx/{{item}}
      loop:
        - sites-available/site.conf
        - snippets/self-signed.conf
        - snippets/ssl-params.conf
    - name: Disable default configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Enable test configuration
      file:
        src: /etc/nginx/sites-available/site.conf
        dest: /etc/nginx/sites-enabled/site.conf
        state: link
    - name: Generate SSL sertificate
      script: ssl/certificate.sh
      args:
        creates: /etc/ssl/certs/nginx-selfsigned.crt
    - name: Reload nginx
      service:
        name: nginx.service
        state: reloaded
    