- name: Install and config MySQL
  hosts: database
  become: true
  become_user: root
  vars_files:
    - "../vars.yml"
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
    - name: Install MySQL and needed libraries
      apt:
        name: ['mysql-server', 'mysql-client', 'python3-pymysql'] 
        state: present
    - name: Change root password
      mysql_user:
        name: root
        password: "{{db_root_pass}}"
        host: "localhost"
        priv: "*.*:ALL,GRANT"
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Copy root credentials for future logins
      template:
        src: mysql/my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: '0400'
    - name: Create opencart db
      mysql_db:
        name: "{{db_opencart_db}}"
        state: present
    - name: Create opencart user
      mysql_user:
        name: "{{db_opencart_user}}"
        password: "{{db_opencart_pass}}"
        host: '192.168.56.30'
        state: present
        priv: "{{db_opencart_db}}.*:ALL"
    - name: Add remote binding
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address.*$'
        replace: 'bind-address = 127.0.0.1,{{db_ip}}'  
    - name: Restart MySQL daemon
      service:
        name: mysql
        state: restarted
